### ISSUE TITLE
Problem with style in Switch

### ISSUE THREAD

**Issue by agrass** [xinthink/react-native-material-kit#245]
Hi, I have an issue when I change the status of switch It show a few seconds with bad style format. Like this:

![captura de pantalla 2016-09-30 a las 10 08 32 a m](https://cloud.githubusercontent.com/assets/1148266/18992697/28586370-86f6-11e6-85cf-c68f98efc521.png)

Anyone know how to solve this?

I'm working with RN 0.26.2 and RMMK 0.3.2

Thanks!

**Comment by Crash--** [comment]
Can you try with the master branch? I know I fixed a bug with State & Switch few weeks ago but not released yet.

**Comment by frederickfogerty** [comment]
@Crash-- Hi, I'm having a problem with Switches as well. How do I use the master branch, do I just use the git repo as my target for npm?

**Comment by frederickfogerty** [comment]
I can confirm `master` fixes my problem, it was around `getThumb()` returning null when trying the toggle the checked state of the Switch.

**Comment by frederickfogerty** [comment]
Unfortunately it does not fix this problem 😢 

![image](https://cloud.githubusercontent.com/assets/615334/19139197/e5d9f6d8-8bde-11e6-868f-86580ec57a7b.png)

Steps to reproduce:

1. Render a switch with `<MKSwitch checked={false} />`
2. Update the switch so checked is now true programmatically (i.e. don't update by clicking) - the thumb won't move but will change colour. `<MKSwitch checked={true} />`
3. Click the thumb to toggle the switch off - the switch will move left of the track. 

The opposite can be done for the other side quite easily.

**Comment by cbartondock** [comment]
I have the same graphical issue and it appears regardless of whether I set checked via a prop

**Comment by cbartondock** [comment]
Nevermind it doesn't happen when I don't have onPress set

**Comment by zachdixon** [comment]
Seems to be an issue with the animation as it doesn't occur with `onCheckedChange` but happens with `onPress`. using `onCheckedChange` [doesn't animate](https://github.com/xinthink/react-native-material-kit/issues/268) the switch though.
